### PR TITLE
Add pickling support for NullarySpore

### PR DESCRIPTION
**Pull request by jvican**
- Make `NullarySpore` to behave as a normal `Spore`. When they don't
  capture any environment, they have the following type refinement: `type
  Captured = Nothing`.
- Add all the necessary picklers and unpickler for any possible kind of
  `Spore`s.

### CODE REVIEW

**Comment by heathermiller** [comment]
Just thinking... Some of this work on nullary spores should probably be added to the spec (SIP-21)

**Comment by jvican** [comment]
I agree Heather, I'll do that as soon as it's merged. I'm preparing the release notes in another PR and I'll address this soon. Ideally, we'd like not to only add these changes to the spec, but reword some parts of it to make the goals of spores crystal clear for potential users (or maybe choose more real-world/compelling examples?). Since some people showed concerns in the past, the clearer we make the SIP, the better. If you're ok with it, I could prepare a draft.

**Comment by jvican** [comment]
BTW, this PR cannot be merged until #46 lands.

**Comment by heathermiller** [comment]
Yes! Please do draft up your changes :)

**Pull request closed without merging**
